# Project policies.
#
# These policies can be enforced using `cargo deny check`.

[licenses]
# Don't allow code with an unclear license.
unlicensed = "deny"

# Don't allow "copylefted" licenses unless they're listed below.
copyleft = "deny"

# Allow common non-restrictive licenses. ISC is used for various DNS and crypto
# things, and it's a minimally restrictive open source license.
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "CC0-1.0", "ISC", "OpenSSL", "Zlib"]

# Many organizations ban AGPL-licensed code
# https://opensource.google/docs/using/agpl-policy/
deny = ["AGPL-3.0"]

# Some slightly odder licenses. MPL-2.0 is a long and complicated "copyleft"
# license that's less strict than the GPL. 
exceptions = [
    { name = "slog-json", allow = ["MPL-2.0"] },
]

[[licenses.clarify]]
# Ring has a messy license. We should either commit 100% to ring everywhere, or
# to native-tls everywhere, and not mix the two.
name = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [
    { path = "LICENSE", hash = 3171872035 },
]

[bans]
# Warn about multiple versions of the same crate, unless we've indicated otherwise below.
multiple-versions = "warn"

skip = [
    # A bunch of libraries still haven't upgraded this.
    { name = "generic-array", version = "0.12.3" },
    # mio v0.6.21 still uses this old version for some reason.
    { name = "miow", version = "0.2.1" },
    # clap v2.33.0 still uses an older version.
    { name = "strsim", version = "0.8.0" },
    # headers v0.3.2 still uses an older version.
    { name = "sha-1", version = "0.8.2" },
]

skip-tree = [
    # postgis pulls in tons of older duplicates that we don't want, but it's
    # still worth the price for now. We should offer to update these depdencies
    # upstream.
    { name = "postgis" },

    # We're going to completely get rid of slog, so we don't care if it
    # introduces duplicate dependencies.
    { name = "slog-term" },
    { name = "slog-envlogger" },

    # This needs updates.
    { name = "rustls-native-certs" },
]


